django/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

django/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns =  [
   path('movies',views.MovieList.as_view(),name='MovieList'),
   path('movie/<int:pk>',views.MovieDetail.as_view(),name='MovieDetail'),
]

django/core/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
   NOT_RATED = 0
   RATED_G = 1
   RATED_PG= 2
   RATED_R = 3
   RATINGS = (
      (NOT_RATED, 'NR - Not Rated'),
      (RATED_G, 'G - General Audiences'),
      (RATED_PG, 'PG - Parential Guidance Suggested'),
      (RATED_R, 'R - Restricted'),
   )

   title = models.CharField(max_length=140)
   plot = models.TextField()
   year = models.PositiveIntegerField()
   reiting = models.IntegerField(choices=RATINGS, default=NOT_RATED)
   runtime = models.PositiveIntegerField()
   website = models.URLField(blank=True)

   def __str__(self):
      return '{} ({})'.format(self.title, self.year)

django/core/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from core.models import Movie

class MovieList(ListView):
   model = Movie

class MovieDetail(DetailView):
   model = Movie

django/core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.title }} - {{ block.super}}
{% endblock%}

{% block main %}
   <h1>{{ object }}</h1>
   <p class="lead">{{ object.plot }}</p>
{% endblock %}

{% block sidebar %}
   <div>
     This movie is rated:
     <span class="badge badge-primary">
        {{ object.get_rating_display }}
     </span>
   </div>
{% endblock %}

django/core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block title %}
    
{% endblock %} 
<ul>
 {% for movie in object_list %}
    <li>{{ movie }}</li>
 {% empty %}
    <li> No movies yet. </li>
 {% endfor %}
</ul>
<p>
 Using https?
 {{ request.s_secure|yesno }}
</p>

django/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>
       {% block title  %}MYMDB{% endblock %}
    </title>
    <style>
        .mymdb-masthead {background-color: #EEEEEE; margin-bottom: 1em;}
    </style>
  </head>
  <body>
    <div class="mymdb-masthead">
       <div class="container">
           <nav class="nav">
              <div class="navbar-brand">MyMDB</div>
              <a class="nav-link" href="{% url 'core:MovieList' %}">Movies</a>
           </nav>
       </div>
    </div>
    
    <div class="container">
        <div class="row">
            <div class="col-sm-8 mymdb-main">
                {% block main %}{% endblock %}
            </div>
            <div class="col-sm-3 offset-sm-1 mymdb-sidebar">
                {% block sidebar %}{% endblock %}
            </div>
        </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>